//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siftables {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siftables.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string AppAbortedCaption {
            get {
                return ResourceManager.GetString("AppAbortedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application aborted due to exception.
        /// </summary>
        public static string AppAbortedMessage {
            get {
                return ResourceManager.GetString("AppAbortedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application aborted.
        /// </summary>
        public static string AppAbortedStatus {
            get {
                return ResourceManager.GetString("AppAbortedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing number of cubes.
        /// </summary>
        public static string ChangingNumberStatus {
            get {
                return ResourceManager.GetString("ChangingNumberStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a Program.
        /// </summary>
        public static string LoadAProgram {
            get {
                return ResourceManager.GetString("LoadAProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program loader was closed..
        /// </summary>
        public static string LoaderClosed {
            get {
                return ResourceManager.GetString("LoaderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load application.
        /// </summary>
        public static string LoadingError {
            get {
                return ResourceManager.GetString("LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application loading failed..
        /// </summary>
        public static string LoadingFail {
            get {
                return ResourceManager.GetString("LoadingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image resources....
        /// </summary>
        public static string LoadingImagesStatus {
            get {
                return ResourceManager.GetString("LoadingImagesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application....
        /// </summary>
        public static string LoadingStatus {
            get {
                return ResourceManager.GetString("LoadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was loaded..
        /// </summary>
        public static string LoadingSuccess {
            get {
                return ResourceManager.GetString("LoadingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Cubes:.
        /// </summary>
        public static string NumOfCubes {
            get {
                return ResourceManager.GetString("NumOfCubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the application to run..
        /// </summary>
        public static string SelectAppStatus {
            get {
                return ResourceManager.GetString("SelectAppStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapping to grid.
        /// </summary>
        public static string SnappingStatus {
            get {
                return ResourceManager.GetString("SnappingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to Grid.
        /// </summary>
        public static string SnapToGrid {
            get {
                return ResourceManager.GetString("SnapToGrid", resourceCulture);
            }
        }
    }
}
